version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    command: >
      sh -c "
      python manage.py migrate &&
      echo 'Step 2: Loading user fixtures...' &&
      python manage.py loaddata fixtures/users.json &&
      echo 'Step 3: Starting Gunicorn server...' &&
      gunicorn CNStyleShop.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.routers.${PREFIX}-router.rule=PathPrefix(`/${PREFIX}`)"
      - "traefik.http.routers.${PREFIX}-router.entrypoints=web"
      - "traefik.http.routers.${PREFIX}-router.middlewares=${PREFIX}-stripprefix-middleware@docker"

      - "traefik.http.middlewares.${PREFIX}-stripprefix-middleware.stripprefix.prefixes=/${PREFIX}"

      - "traefik.http.services.${PREFIX}-service.loadbalancer.server.port=${EXPOSEPORT}"

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
  traefik-public:
    external: true
