# Generated by Django 5.1.5 on 2025-03-11 20:53

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("total_price", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(choices=[("slip", "แนบสลิป")], max_length=50),
                ),
                (
                    "payment_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=orders.models.upload_to
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการชำระเงิน"),
                            ("paid", "จ่ายแล้ว"),
                            ("completed", "สำเร็จ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("unit_price", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
