# Generated by Django 5.1.5 on 2025-03-11 20:53

import django.core.validators
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("blouse", "เสื้อเบล้าส์"),
                            ("dress", "ชุดเดรส"),
                            ("jacket", "แจ็คเก็ต"),
                            ("jeans", "ยีนส์"),
                            ("shirt", "เสื้อเชิ้ต"),
                            ("tshirt", "เสื้อยืด"),
                            ("shorts", "กางเกงขาสั้น"),
                            ("skirt", "กระโปรง"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to=products.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"],
                                message="กรุณาอัปโหลดไฟล์ที่มีนามสกุล .jpg, .jpeg, หรือ .png เท่านั้น",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "สินค้า",
                "verbose_name_plural": "สินค้าทั้งหมด",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=products.models.upload_gallery)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปภาพสินค้าเพิ่มเติม",
                "verbose_name_plural": "รูปภาพสินค้าเพิ่มเติมทั้งหมด",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตัวเลือกสินค้า",
                "verbose_name_plural": "ตัวเลือกสินค้าทั้งหมด",
            },
        ),
    ]
